export const GET_BRANDS = 'GET_BRANDS'
export const BRANDS_ERROR = 'BRANDS_ERROR'
export const GET_ITEMS = 'GET_ITEMS'
export const ITEMS_ERROR = 'ITEMS_ERROR'

export const ADD_ITEM_TO_BUCKET = 'ADD_ITEM_TO_BUCKET'
export const REMOVE_ITEM_FROM_BUCKET = 'REMOVE_ITEM_FROM_BUCKET'

export const SET_ACTIVE_FILTERS = 'SET_ACTIVE_FILTERS'
